import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nav3',
  templateUrl: './nav3.component.html',
  styleUrls: ['./nav3.component.css']
})
export class Nav3Component implements OnInit {
  imgs: Array<string> = [
    '001.jpg',
    '002.jpg',
    '003.jpg',
    '004.jpg',
    '005.jpg',
    '006.jpg',
    '007.jpg',
    'c0.1.jpg',
    'c01.jpg',
    'c02.jpg',
    'c03.jpg',
    'c04.jpg',
    'c05.jpg',
    'c06.jpg',
    'c07.jpg',
    'c08.jpg',
    'c09.jpg',
    'c10.jpg',
    'c11.jpg',
    'c12.jpg',
    'c13.jpg',
    'c14.jpg',
    'c15.jpg',
    'c16.jpg',
    'c17.jpg',
    'c18.jpg',
    'c19.jpg',
    'c20.jpg',
    'c21.jpg',
    'c22.jpg',
    'c24.jpg',
    'c25.jpg',
    'c26.jpg',
    'c27.jpg',
    'c28.jpg',
    'c29.jpg',
    'c32.jpg',
    'c36.jpg',
    'c40.jpg',
    'c42.jpg',
    'c45.jpg',
    'EVER GREEN 1.jpg',
    'EVER GREEN 2.jpg',
    'EVER GREEN 3.jpg',
    'EVER GREEN 4.jpg',
    'EVER GREEN 5.jpg',
    'EVER GREEN 6.jpg',
    'EVER GREEN 7.jpg',
    'EVER GREEN 8.jpg',
    'EVER GREEN 9.jpg',
    'EVER GREEN 10.jpg',
    'EVER GREEN 11.jpg',
    'EVER GREEN 12.jpg',
    'EVER GREEN 13.jpg',
    'EVER GREEN 14.jpg',
    'EVER GREEN 15.jpg',
    'EVER GREEN 16.jpg',
    'm1.jpg',
    'm2.jpg',
    'm3.jpg',
    'm4.jpg',
    'm5.jpg',
    'm6.jpg',
    'm7.jpg',
    'm8.jpg',
    'm9.jpg',
    'm10.jpg',
    'm11.jpg',
    'm12.jpg',
    'm13.jpg',
    'm14.jpg',
    'm15.jpg',
  ];
  constructor() { }

  ngOnInit() {
  }

}
